CREATE TABLE IF NOT EXISTS `Users` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	`username` VARCHAR(100) NOT NULL UNIQUE,
    `email` VARCHAR(100) NOT NULL,
	`password` VARCHAR(60) NOT NULL,
	`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	'number' VARCHAR(15) DEFAULT NULL,
	`2fa` TINYINT(1) NOT NULL DEFAULT 0,
  	'code' VARCHAR(6) DEFAULT NULL
)
;
